name = "ArkType"
grammar = "arktype"
path_suffixes = ["arktype", "ark"]
line_comments = ["// "]
tab_size = 2

brackets = [
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false },
  { start = "'", end = "'", close = true, newline = false },
]
